- name: SettingUp Redis Repo
  ansible.builtin.copy:
   src: redis.repo
   dest: /etc/yum.repos.d/redis.repo


- name: installing Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Updating redis config file
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: "127.0.0.1"
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf


- name: restarting redis file
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes



