- name: Install GoLang
  yum:
    name: golang
    state: installed

- name: Setup Appuser and Application
  import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENTS}} Dependences
  ansible.builtin.shell: go mod init {{COMPONENT}} && go get && go build
  args:
    chdir: /home/roboshop/{{COMPONENT}}
    become_user: roboshop

- name: Configure Systemd for {{COMPONENT}}
  import_role:
    name: common
    tasks_from: systemd

