- name: Setup Repo file for NodeJS
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo
## Coping the nodejs.repo files from roles folder to the remote system using ansible.bultin.copy module

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed
## Installing nodeJS files in frontend machine using ansible module, here 2 packages are getting installed in a single take.

- name: Setup APP user and app code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop
#Perofrming npmrebult command with the help of ansible module


- name: Setup {{COMPONENT}} SystemD Config File
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

 #coping the systemd.service  from template folder to systemd folder

- name: Start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

##Restarting the services

