- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Import App user and app code
  ansible.builtin.import:
    name: common
    tasks_from: download


