- name: setup YUM repo for RabbitMq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash


- name: Installing RabbitMq and the Supporting components
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    state: installed

- name: Starting RabbitMq Services
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes


- name: Setup RoboShop Application User in RabbitMQ
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present



