- name: Setup Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - frontend

- name: Setup cart Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - cart


