- name: Setup Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - frontend

- name: Setup MongoDBComponent
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - mongo

- name: Setup cart Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - cart

- name: Setup user Component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - user



