- name: Variable on Play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# Note: If we declare a varibale in PLAY level then all the tasks can access that variable.