- name: Variable on Play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# Note: If we declare a varibale in PLAY level then all the tasks can access that variable.

- name: variable printing from a File
  hosts: all
  vars_files:
    - sample_vars.yml
  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# We can load all the variables from a file, Since it is on play level, all the tasks can access those variables

- name: variable declearing in task level
  hosts: all
  tasks:
    - name: print url
      ansible.builtin.debug:
      vars:
        URL: www.sherwin.com
        msg: URL == {{URL}}

    - name: print url
      ansible.builtin.debug:
      vars:
        URL: www.zubin.com
        msg: URL == {{URL}}